[package]
name = "process-event"
version = "0.4.1"
authors = ["Sentry <hello@getsentry.com>"]
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.56"
reqwest = { version = "0.11.0", features = ["blocking", "json", "multipart"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.61"
structopt = "0.3.21"
